#!/usr/bin/env python3
"""Rebuild the Icons section of mist.css from tools/icon-map.txt.

Each Jellyfin icon in the map is redrawn with a Lucide icon: the icon is
embedded as an SVG mask and painted in the text colour, so hover, focus
and "played" colours keep working.

    python3 tools/icons.py
"""
import json
import re
import urllib.request
from pathlib import Path

LUCIDE_VERSION = "1.48.0"
CDN = f"https://cdn.jsdelivr.net/npm/lucide-static@{LUCIDE_VERSION}"
ROOT = Path(__file__).resolve().parent.parent
CSS = ROOT / "mist.css"
MAP = ROOT / "tools" / "icon-map.txt"
START = "/* ---------- Icons ----------"
END = "/* ---------- Login ---------- */"


def fetch(path):
    with urllib.request.urlopen(f"{CDN}/{path}", timeout=30) as r:
        return r.read().decode()


def read_map():
    font, mui = [], []
    for line in MAP.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        key, icon, *flags = line.split()
        kind, name = key.split(":", 1)
        (font if kind == "font" else mui).append((name, icon, "fill" in flags))
    return font, mui


def svg_url(nodes, filled):
    inner = "".join(
        "<%s %s/>" % (tag, " ".join(f"{k}='{v}'" for k, v in attrs.items() if k != "key"))
        for tag, attrs in nodes
    )
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' "
           f"fill='{'%23000' if filled else 'none'}' stroke='%23000' stroke-width='2' "
           f"stroke-linecap='round' stroke-linejoin='round'>{inner}</svg>")
    return 'url("data:image/svg+xml,' + svg.replace("<", "%3C").replace(">", "%3E") + '")'


# Lucide renamed some icons it took from Feather; its LICENSE lists the
# Feather names
FEATHER_RENAMES = {
    "alert-triangle": "triangle-alert",
    "help-circle": "circle-question-mark",
    "more-horizontal": "ellipsis",
    "more-vertical": "ellipsis-vertical",
}


def feather_icons(license_text, used):
    listed = re.search(r"derived from the Feather project:\s*(.*?)\n\n", license_text, re.S)
    names = {n.strip() for n in listed.group(1).split(",")} if listed else set()
    for name in list(names):
        names.add(FEATHER_RENAMES.get(name, name))
        if name.endswith("-circle"):            # x-circle is now circle-x
            names.add("circle-" + name[: -len("-circle")])
    return sorted(used & names)


def build():
    nodes = json.loads(fetch("icon-nodes.json"))
    license_text = fetch("LICENSE")
    font, mui = read_map()
    rows = font + mui + [("heart-filled", "heart", True)]
    missing = sorted({icon for _, icon, _ in rows if icon not in nodes})
    if missing:
        raise SystemExit(f"Not in Lucide {LUCIDE_VERSION}: {', '.join(missing)}")

    def token(icon, filled):
        return f"--mist-icon-{icon}{'-fill' if filled else ''}"

    tokens = sorted({(icon, filled) for _, icon, filled in rows})
    used = {icon for icon, _ in tokens}
    feather = feather_icons(license_text, used)

    out = [START, """
   Jellyfin's icons are redrawn with Lucide's line icons. Each one is
   an SVG mask painted in the text colour, so hover, focus and "played"
   colours still apply; browsers without CSS masks keep Jellyfin's
   icons. Icons that Jellyfin's React screens write out as text (the
   library links in the new header, and library and plugin icons in the
   dashboard) can't be matched by CSS and keep Jellyfin's icons too.
   Generated by tools/icons.py from tools/icon-map.txt: edit the map and
   rerun the script rather than editing this section by hand.

   Lucide (https://lucide.dev), ISC License,
   Copyright (c) 2026 Lucide Icons and Contributors.
   Permission to use, copy, modify, and/or distribute this software for any
   purpose with or without fee is hereby granted, provided that the above
   copyright notice and this permission notice appear in all copies.
   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
   OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""]
    if feather:
        lines, line = [], "  "
        for name in feather:
            if len(line) + len(name) > 70:
                lines.append(line.rstrip())
                line = "  "
            line += f" {name},"
        lines.append(line.rstrip(","))
        out.append("   These come from Feather (https://feathericons.com):\n" + "\n".join(" " + l for l in lines) + """
   MIT License, Copyright (c) 2013-present Cole Bemis.
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the
   "Software"), to deal in the Software without restriction, including
   without limitation the rights to use, copy, modify, merge, publish,
   distribute, sublicense, and/or sell copies of the Software, and to
   permit persons to whom the Software is furnished to do so, subject to
   the following conditions: The above copyright notice and this
   permission notice shall be included in all copies or substantial
   portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
   WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
   THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
""")
    out[-1] = out[-1].rstrip("\n") + " */\n"

    out.append(":root {\n" + "\n".join(
        f"  {token(icon, filled)}: {svg_url(nodes[icon], filled)};" for icon, filled in tokens) + "\n}\n")

    body = ["@supports ((mask-image: none) or (-webkit-mask-image: none)) {"]
    body.append("  /* font icons: <span class=\"material-icons NAME\"> */")
    body += [f"  .material-icons.{name} {{ --mist-icon: var({token(icon, filled)}); }}" for name, icon, filled in font]
    body.append("  /* a favourite fills its heart */")
    body.append(f"  .material-icons.favorite.ratingbutton-icon-withrating {{ --mist-icon: var({token('heart', True)}); }}")
    body.append("  .material-icons:is(" + ", ".join(f".{n}" for n, _, _ in font) + ")::before {")
    body.append("""    content: "" !important;
    display: block;
    width: 1em;
    height: 1em;
    background-color: currentColor;
    -webkit-mask: var(--mist-icon) center / contain no-repeat;
    mask: var(--mist-icon) center / contain no-repeat;
  }""")
    body.append("  /* MUI icons: <svg data-testid=\"NAMEIcon\">; the SVG's own drawing is hidden */")
    body += [f"  .MuiSvgIcon-root[data-testid=\"{name}Icon\"] {{ --mist-icon: var({token(icon, filled)}); }}" for name, icon, filled in mui]
    sel = "  .MuiSvgIcon-root:is(" + ", ".join(f"[data-testid=\"{n}Icon\"]" for n, _, _ in mui) + ")"
    body.append(sel + " {")
    body.append("""    background-color: currentColor;
    -webkit-mask: var(--mist-icon) center / contain no-repeat;
    mask: var(--mist-icon) center / contain no-repeat;
  }""")
    body.append(sel + " > * { visibility: hidden; }")
    body.append("}\n\n")
    out.append("\n".join(body))

    css = CSS.read_text()
    a, b = css.index(START), css.index(END)
    CSS.write_text(css[:a] + "".join(out) + css[b:])
    print(f"{len(font)} font icons and {len(mui)} MUI icons drawn with {len(used)} Lucide icons")


if __name__ == "__main__":
    build()
