#!/usr/bin/env python3
"""Redraw Jellyfin's MUI SVG icons with Material Symbols Rounded.

Reads tools/mui-icons.txt, downloads each icon's 24px SVG from Google
Fonts, and rewrites the block between the mui-icons markers in mist.css.
Run from anywhere: python3 tools/mui-icons.py
"""
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAP = ROOT / "tools" / "mui-icons.txt"
CSS = ROOT / "mist.css"
URL = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{name}/{style}/24px.svg"
START = "/* mui-icons:start (generated by tools/mui-icons.py) */"
END = "/* mui-icons:end */"


def fetch(name, fill):
    url = URL.format(name=name, style="fill1" if fill else "default")
    req = urllib.request.Request(url, headers={"User-Agent": "mist-theme"})
    try:
        svg = urllib.request.urlopen(req).read().decode()
    except Exception as e:
        sys.exit(f"{name}: {e} ({url})")
    svg = re.sub(r'\s(width|height)="\d+"', "", svg)
    for a, b in (('"', "'"), ("%", "%25"), ("#", "%23"), ("<", "%3C"), (">", "%3E")):
        svg = svg.replace(a, b)
    return f'url("data:image/svg+xml,{svg}")'


rows = []
for line in MAP.read_text().splitlines():
    line = line.split("#", 1)[0].split()
    if line:
        rows.append((line[0], line[1], "fill" in line[2:]))

sel = ", ".join(f'[data-testid="{mui}Icon"]' for mui, _, _ in rows)
out = [START, "@supports ((mask-image: none) or (-webkit-mask-image: none)) {"]
for mui, name, fill in rows:
    out.append(f'  .MuiSvgIcon-root[data-testid="{mui}Icon"] {{ --mist-icon: {fetch(name, fill)}; }}')
out += [
    f"  .MuiSvgIcon-root:is({sel}) {{",
    "    background-color: currentColor;",
    "    -webkit-mask: var(--mist-icon) center / contain no-repeat;",
    "    mask: var(--mist-icon) center / contain no-repeat;",
    "  }",
    f"  .MuiSvgIcon-root:is({sel}) > * {{ visibility: hidden; }}",
    "}",
    END,
]

css = CSS.read_text()
i, j = css.index(START), css.index(END) + len(END)
CSS.write_text(css[:i] + "\n".join(out) + css[j:])
print(f"{len(rows)} MUI icons written to {CSS.name}")
